### PR TITLE
Add support for Django 1.8

### PR DESCRIPTION
**Pull request by dhui**
This is blocked by django_nose since django_nose doesn't support Django 1.8 yet.

https://github.com/django-nose/django-nose/issues/178
https://github.com/django-nose/django-nose/issues/186

### CODE REVIEW

**Comment by dhui** [comment]
Looks like django_nose release version 1.4 which supports Django 1.8
However, django_richenum is hitting metaclass issues with Django 1.8

Here's the error:
```
Traceback (most recent call last):
  File "setup.py", line 96, in <module>
    cmdclass={'test': DjangoTest},
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/test.py", line 142, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/test.py", line 122, in with_project_on_sys_path
    func()
  File "setup.py", line 71, in run_tests
    django.setup()  # pylint: disable=no-member
  File "/Users/dale/projects/hearsay/django-richenum/.eggs/Django-1.8-py2.7.egg/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/dale/projects/hearsay/django-richenum/.eggs/Django-1.8-py2.7.egg/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/dale/projects/hearsay/django-richenum/.eggs/Django-1.8-py2.7.egg/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/dale/projects/hearsay/django-richenum/tests/models.py", line 3, in <module>
    from django_richenum.models import IndexEnumField
  File "/Users/dale/projects/hearsay/django-richenum/src/django_richenum/__init__.py", line 1, in <module>
    import forms  # noqa
  File "/Users/dale/projects/hearsay/django-richenum/src/django_richenum/forms/__init__.py", line 1, in <module>
    from .fields import CanonicalEnumField  # noqa
  File "/Users/dale/projects/hearsay/django-richenum/src/django_richenum/forms/fields.py", line 98, in <module>
    class CanonicalEnumField(_BaseCanonicalField, forms.TypedChoiceField):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/abc.py", line 87, in __new__
    cls = super(ABCMeta, mcls).__new__(mcls, name, bases, namespace)
TypeError: Error when calling the metaclass bases
    metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

Looks like the culprit is the Field class.
In Django 1.7, the class declaration looks like:
```python
class Field(object):
```
But in Django 1.8, the class declaration looks like:
```python
class Field(six.with_metaclass(RenameFieldMethods, object)):
```

**Comment by dhui** [comment]
Oh, travis tests are failing b/c of `pylint-django`...
I haven't had time to figure out why.

**Comment by adepue** [comment]
No worries I'll look

**Comment by dhui** [comment]
Awesome, thanks!

**Pull request closed without merging**
