### PR TITLE
Support django 1.10

### PR DESCRIPTION
**Pull request by adepue**
/review @RVoigtHearsay @asherf @droanr @jasonbot @jtillman @olakd @rogerhu @tomo-otsuka @vcoste

### CODE REVIEW

**Comment by dhui** [comment]
Dang! Already moving to Django 1.10?!

Looks like there are some `SubfieldBase` issues. https://docs.djangoproject.com/en/1.9/howto/custom-model-fields/#converting-values-to-python-objects

**Comment by adepue** [comment]
Just prepping @dhui :)

**Comment by adepue** [comment]
Tests passing now

**Comment by asherf** [comment]
lgtm

**Pull request merged**
