### PR TITLE
Support Django 3

### PR DESCRIPTION
**Pull request by dhui**

### CODE REVIEW

**Comment by rbm** [comment]
Thanks Dale!

It looks like Travis isn't wired up to pull requests for this repository anymore. Not sure what happened there. I'll check on that and get this merged this weekend.

**Comment by dhui** [comment]
Hey Robert! 👋 

Yeah, not sure what happened w/ the Github Travis CI integration. Maybe it's still using the [deprecated](https://developer.github.com/v3/guides/replacing-github-services/#deprecation-timeline) legacy services integration?

But, the tests [ran and passed](https://travis-ci.org/github/hearsaycorp/django-richenum/builds/671040361) for this PR.

**Comment by dhui** [comment]
Pulled master so tests run on the PR

**Comment by rbm** [comment]
@dhui 3.8 is up on PyPI: https://pypi.org/project/django-richenum/3.8.0/

Sorry for the delay. Switching to Actions took a lot longer than I thought, and I've got a day job that doesn't permit a lot of noodling with Docker and Tox ;)

**Comment by dhui** [comment]
Thanks for the merge and no worries about the delay!

**Pull request merged**
