### PR TITLE
switch to tox

### PR DESCRIPTION
**Pull request by asherf**

### CODE REVIEW

**Comment by dhui** [comment]
Not sure why Travis (or another CI) system isn't running and reporting back to Github

**Comment by asherf** [comment]
> Not sure why Travis (or another CI) system isn't running and reporting back to Github

@dhui wdym ? seems fine to me...
Screenshot 2019-07-08 10 01 48

**Comment by dhui** [comment]
Oh weird, TravisCI appears now...

I took a look at the latest build output and don't see the cross product of tests of Python versions and Django versions. Does using tox remove the cross product of tests?

**Comment by asherf** [comment]
@dhui it still tests all the desired combinations.
only with less travis jobs. all the python 3.6 variations are tested under one travis job:
Screenshot 2019-07-08 13 06 17


https://travis-ci.org/hearsaycorp/django-richenum/jobs/555868882#L431

**Comment by asherf** [comment]
@rbm @rogerhu

**Comment by rbm** [comment]
lgtm

**Comment by dhui** [comment]
:shipit:

**Pull request merged**
