### PR TITLE
properly mark raw strings (used as regex)

### PR DESCRIPTION
**Pull request by asherf**

### CODE REVIEW

**Comment by dhui** [comment]
Changes LGTM but the commit message is misleading. `r` doesn't designate a regex, it means it's a raw string. https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals

**Comment by dhui** [comment]
Looks like there's an issue w/ pylint_django, for which there are 2 proposed fixes:
* https://github.com/landscapeio/pylint-django/pull/109
* https://github.com/landscapeio/pylint-django/pull/111

Looks like pinning pylint to and older version will also help get around the issue: https://github.com/landscapeio/pylint-django/issues/108

**Comment by asherf** [comment]
@dhui updated
stacked on top of https://github.com/hearsaycorp/django-richenum/pull/52

**Comment by dhui** [comment]
:shipit:

**Pull request merged**
