### PR TITLE
Use the django_richenum formfields by default in ModelForms

### PR DESCRIPTION
**Pull request by dhui**
Depends on: https://github.com/hearsaycorp/django-richenum/pull/42

### CODE REVIEW

**Comment by asherf** [comment]
@dhui  can u rebase?

**Comment by adepue** [comment]
No rebase conflicts currently

**Comment by dhui** [comment]
Weird, I had to rebase after #42 was merged in to get github to ignore then original 4 commits...

**Comment by asherf** [comment]
Thanks @dhui

**Pull request merged**
