### PR TITLE
Allows more flexibility in what can be interpretted as an integer

### PR DESCRIPTION
**Pull request by animan1**
@adepue @rogerhu

### CODE REVIEW

**Comment by adepue** [comment]
@akshayjshah  @dhui  any thoughts?

**Comment by akshayjshah** [comment]
Caveat for all that follows: I don't think I'm in a position to veto anything in this repo anymore :)

@animan1 What's the use case for this? I'm generally opposed to, for example, silently coercing floats to ints...let alone random user-defined types that implement `__int__`.

Also, needs tests. Maybe a test case can illustrate the use you have in mind?

**Comment by animan1** [comment]
I'll write a test, but the case that I am considering is for string/unicode values such as '1'. These get loaded from JSON or GET parameters with some frequency. While they can be explicitly coerced when creating the model, it's an extra gotcha. It seems more pythonic to allow things that can be interpreted as an integer to be interpreted that way rather than explicitly making the user do it. I can specifically call out the string/unicode cases or specifically disallow floating point truncation if that is preferred.

**Comment by akshayjshah** [comment]
I'll defer to @adepue and anyone else who'll have to live with the consequences of any changes. 

Personally, I'm not a fan - the purpose of this library is to bring some type safety to enums. Re: JSON, why are we encoding ints as strings when the serialization format allows something saner? Re: GET params, seems like it's easy enough to coerce them before assigning them to a model field. If we really want this behavior, I'd advocate for putting in `LaxIndexEnumField`, not `IndexEnumField`.

Agreed that this isn't the most Pythonic approach, but the Pythonic approach to enums and type coercion created an enormous mess in `fanmgmt` that took a year to clean up.

**Comment by dhui** [comment]
Agreed with @akshayjshah 

I'm not a fan of coercing strs to ints behind the scenes for Django model fields.
If you're dealing with GET requests, use a Django form with the provided an `IndexEnumField` which will convert the string to an int for you.
https://github.com/hearsaycorp/django-richenum/blob/master/src/django_richenum/forms/fields.py#L80
You should not be passing in unvalidated HTTP request data directly to your Django model.

You can try passing the parsed JSON string (presumably, it becomes a Python dict) to a Django form as well, which should bind the form with values.

If the JSON structure you're parsing is too complicated to represent with a Django form, try using normalize to parse the str as an int and then convert the int to a RichEnum.
https://github.com/hearsaycorp/normalize

**Comment by animan1** [comment]
Yup, definitely a dozen different ways to convert prior to the Django model and even more prior to hitting this library. I went this route because all of the alternatives require writing more code for an IndexEnumField than you would for, say, an IntegerField. Using the IndexEnumField buys you automatic coercion between integers and enums without needing to write a property, but at the cost of requiring coercion logic elsewhere. I can buy type safety as being the reason for this as opposed to using a LaxIndexEnumField which is explicitly less type safe. It appears that all of the suggestions have drawbacks ranging from type safety to code bloat.

I'll wait to hear back about what route we want to go before making further changes to the PR.

**Comment by adepue** [comment]
My $.02 would be to hold the type safety line in this library.  It was meant to bring some type safety to the models and enforce that you are passing through the correct types.

**Pull request closed without merging**
